Project Order{
database_type: 'MySQL'
note: 'This is a university Project. Order is a set of logistic tools that track objects of interest inside of a building'
}

Table Users
{
  id int [pk]
  name char(15)
  surname char(20)
  email varchar
  role char(20)
}


Table Log
{
  id bigint [pk]
  user int [ref: > Users.id]
  date date
  table char(15)
  type action

}

enum action
{
Insert
Update
Delete
}


Table Items
{
  id bigint [pk]
  name char(15)
  category char(15) [ref:> Item_Categories.title]
  supervisor int [ref:> Users.id]
  room int [ref:> Rooms.id]
  exp_date date
  comments varchar
}

Table Item_Categories
{
  title char(15)
}

Table Rooms
{
  id int [pk]
  name char(15)
  floor int(3)
  building int [ref:> Buildings.id]
  categories char(15) [ref:> Room_Categories.name]
}

Table Room_Categories
{
  name char(15)
}

Table Buildings
{
  id int [pk]
  name char(15)
  Address char(100)
}

Table Rights
{
  item bigint [ref:> Items.id]
  room int [ref:> Rooms.id]

  indexes{
    (item,room) [pk]
  }
}


Table Moves
{
id bigint [pk]
origin_room int [ref: > Rooms.id]
destination_room int [ref: > Rooms.id]
building int [ref: > Buildings.id]
timestamp datetime
legal bit
}
